// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: 1.8

#include "ui_b.h"

void ui_comp_Slider1_create_hook(lv_obj_t * comp)
{
}
