// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-AMOLED-1.8

#include "ui_c.h"

void arcincrement(lv_event_t * e)
{
	// Your code here
}

void labelincrement(lv_event_t * e)
{
	// Your code here
}
