// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ESP32-S3-Touch-AMOLED-1.8

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void arcincrement(lv_event_t * e);
void labelincrement(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
